### ISSUE TITLE
v2 ios build failing

### ISSUE THREAD

**Issue by stevensacks** [VISI-ONE/create-react-native-web-app#14]
The issue is Xcode 10 requires react-native 57.x - See below the consequence of updating package.json to 57.x.

**Comment by stevensacks** [comment]
I found this:

```
The problem is because we use Stack with stable channel. Apple did release iOS SDK 12, then inside stack, Xcode upgraded to version 10, and only React Native 0.57+ is compatible with this Xcode Version.```

So you have to update React Native to 57.x (as mentioned in issue #15 )

**Comment by stevensacks** [comment]
I updated react-native to 57.7 and now I get this error on a fresh build:

![screen shot 2018-12-02 at 7 53 22 pm](https://user-images.githubusercontent.com/162252/49338893-112f1800-f66c-11e8-815a-01ef085a0fb8.png)

I googled but couldn't find anything helpful.

**Comment by orYoffe** [comment]
@stevensacks I couldn't upgrade the react-native version as react-native-web supports v0.55 since v0.56 has too big of a difference for them to fix right away (they say if you use anything above 0.55 things probably would break)
https://github.com/necolas/react-native-web
About Xcode 10 take a look at this thread to solve and support legacy build in Xcode for ios
https://github.com/facebook/react-native/issues/19573
